// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: myorg/todo/v1/search.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTodosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchTodosRequest) Reset() {
	*x = SearchTodosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myorg_todo_v1_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTodosRequest) ProtoMessage() {}

func (x *SearchTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myorg_todo_v1_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTodosRequest.ProtoReflect.Descriptor instead.
func (*SearchTodosRequest) Descriptor() ([]byte, []int) {
	return file_myorg_todo_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchTodosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchTodosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todos []*Todo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
}

func (x *SearchTodosResponse) Reset() {
	*x = SearchTodosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myorg_todo_v1_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTodosResponse) ProtoMessage() {}

func (x *SearchTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myorg_todo_v1_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTodosResponse.ProtoReflect.Descriptor instead.
func (*SearchTodosResponse) Descriptor() ([]byte, []int) {
	return file_myorg_todo_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_myorg_todo_v1_search_proto protoreflect.FileDescriptor

var file_myorg_todo_v1_search_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x79, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x79,
	0x6f, 0x72, 0x67, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x6d, 0x79, 0x6f,
	0x72, 0x67, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54,
	0x6f, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x22, 0x40, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x64, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x6f, 0x64, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x79, 0x6f, 0x72, 0x67, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x05, 0x74, 0x6f,
	0x64, 0x6f, 0x73, 0x42, 0x7a, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x79, 0x6f, 0x72, 0x67,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x54, 0x6f, 0x64, 0x6f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4d, 0x79, 0x4f, 0x72, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f,
	0x72, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x79, 0x6f, 0x72,
	0x67, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4d, 0x54, 0x58, 0xaa,
	0x02, 0x0d, 0x4d, 0x79, 0x4f, 0x72, 0x67, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0d, 0x4d, 0x79, 0x4f, 0x72, 0x67, 0x5c, 0x54, 0x6f, 0x64, 0x6f, 0x5c, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myorg_todo_v1_search_proto_rawDescOnce sync.Once
	file_myorg_todo_v1_search_proto_rawDescData = file_myorg_todo_v1_search_proto_rawDesc
)

func file_myorg_todo_v1_search_proto_rawDescGZIP() []byte {
	file_myorg_todo_v1_search_proto_rawDescOnce.Do(func() {
		file_myorg_todo_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_myorg_todo_v1_search_proto_rawDescData)
	})
	return file_myorg_todo_v1_search_proto_rawDescData
}

var file_myorg_todo_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_myorg_todo_v1_search_proto_goTypes = []interface{}{
	(*SearchTodosRequest)(nil),  // 0: myorg.todo.v1.SearchTodosRequest
	(*SearchTodosResponse)(nil), // 1: myorg.todo.v1.SearchTodosResponse
	(*Todo)(nil),                // 2: myorg.todo.v1.Todo
}
var file_myorg_todo_v1_search_proto_depIdxs = []int32{
	2, // 0: myorg.todo.v1.SearchTodosResponse.todos:type_name -> myorg.todo.v1.Todo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_myorg_todo_v1_search_proto_init() }
func file_myorg_todo_v1_search_proto_init() {
	if File_myorg_todo_v1_search_proto != nil {
		return
	}
	file_myorg_todo_v1_todo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_myorg_todo_v1_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTodosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myorg_todo_v1_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTodosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myorg_todo_v1_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myorg_todo_v1_search_proto_goTypes,
		DependencyIndexes: file_myorg_todo_v1_search_proto_depIdxs,
		MessageInfos:      file_myorg_todo_v1_search_proto_msgTypes,
	}.Build()
	File_myorg_todo_v1_search_proto = out.File
	file_myorg_todo_v1_search_proto_rawDesc = nil
	file_myorg_todo_v1_search_proto_goTypes = nil
	file_myorg_todo_v1_search_proto_depIdxs = nil
}
