version: '3.7'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
    - 7700:7700
    command: ["./meilisearch"]

  redis:
    image: library/redis:6.0.7-alpine
    restart: always
    ports:
    - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 14250:14250
    - 9411:9411

  dgraph:
    image: dgraph/standalone:v20.11.2
    ports:
    - 8080:8080
    - 9080:9080
    - 8000:8000
    volumes:
    - dgraphdata:/dgraph

volumes:
  dgraphdata:
  meilisearchdata: